### ISSUE TITLE
Menampilkan data banyak dari Database pada Bot

### ISSUE THREAD

**Issue by imanudin11** [banghasan/telegrambotphpsql#3]
Assalamualaikum bang Hasan,
Terima kasih atas panduan dan source code-nya bang. Saya sudah sukses mengimplementasikannya. Namun ada sedikit kendala jika menampilkan jumlah data yang banyak. Pesan errornya "too long". Apakah memungkinkan untuk menampilkan data yang banyak pada Bot Telegram? seperti pagination pada web. Jika ada clue, boleh disampaikan. Nanti saya coba.

Terima Kasih

**Comment by banghasan** [comment]
too long artinya kepanjangan textnya, max text pada telegram adalah 4kB atau 4096.

solusi: bisa di potong textnya, gunakan fungsi2 yang ada, misalnya split, warp word, dlsb sebelum dikirim.

**Comment by imanudin11** [comment]
Terima kasih clue nya bang Hasan. Saya coba pelajari
